In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import os

In [14]:
%conda install -c pytorch pytorch torchvision

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [16]:
import torch

In [10]:
X=pd.read_csv("Train_ext.csv")

In [12]:
Y=pd.read_csv("Class.csv")

In [11]:
Z=pd.read_csv("Test_ext.csv")

In [17]:
X

,Unnamed: 0,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F25,F26,F27,F28,F29,F30,F31,F32,F33,F34
0,0,127.285160,128.014220,129.049220,23.132183,22.989187,23.550589,-0.300963,-0.312428,-0.305175,...,0.198341,22.986380,0.000363,881.44050,0.171260,23.502848,0.000357,907.04840,0.146760,23.971640
1,1,123.675316,124.864530,125.766250,17.833525,18.399496,18.087454,0.246668,0.214148,0.209875,...,-0.001439,20.156706,0.000452,680.20935,-0.028413,20.362183,0.000453,695.33453,-0.047140,20.576350
2,2,132.912500,133.320470,132.442660,25.895767,25.280909,23.832703,0.305303,0.368690,0.455977,...,-0.052314,29.969877,0.000290,1368.54590,-0.069415,30.148418,0.000292,1390.66440,-0.084887,30.371254
3,3,110.283905,113.433280,116.918750,30.094240,27.083897,24.573830,0.492504,-0.017867,-0.921990,...,0.009663,26.342894,0.000498,1508.64470,-0.003699,26.670254,0.000491,1527.80180,-0.017576,27.039417
4,4,91.065940,106.395000,118.473750,20.735636,20.307592,19.412655,1.985061,1.934323,1.916436,...,0.032211,19.772793,0.000550,807.46770,0.019337,19.910126,0.000544,829.33936,-0.000955,20.209100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,695,116.856560,114.497345,111.954840,41.003567,38.772100,36.618973,0.569956,0.620960,0.647937,...,0.210192,37.396090,0.000225,2455.31570,0.198277,37.753640,0.000230,2491.52880,0.187167,37.971317
696,696,159.455780,151.456250,143.326870,43.487637,42.923706,38.616272,-0.854458,-0.841975,-0.881015,...,0.015246,47.091972,0.000224,3693.84030,-0.006851,47.803320,0.000226,3756.04050,-0.026491,48.188270
697,697,134.612980,132.746570,128.173900,45.607872,43.689130,41.025510,-0.326999,-0.330075,-0.334550,...,0.115463,46.382470,0.000202,3476.26540,0.099332,46.946045,0.000199,3514.17240,0.088212,47.377182
698,698,125.118126,124.585000,124.452190,32.311893,29.621923,26.401573,0.339743,0.328440,0.272559,...,0.155644,30.449928,0.000263,1492.23390,0.164374,30.227848,0.000263,1495.68580,0.162392,30.338568
699,699,111.085310,111.054220,111.086716,44.621025,43.527970,41.746906,0.445195,0.357870,0.237632,...,0.289028,39.423650,0.000226,2743.13750,0.280644,39.682438,0.000228,2779.69210,0.271496,40.099503

In [18]:
Y

     Unnamed: 0    0
0             0  0.0
1             1  0.0
2             2  0.0
3             3  0.0
4             4  0.0
..          ...  ...
695         695  1.0
696         696  1.0
697         697  1.0
698         698  1.0
699         699  1.0

[700 rows x 2 columns]

In [19]:
Z

,Unnamed: 0,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F25,F26,F27,F28,F29,F30,F31,F32,F33,F34
0,0,122.072815,121.53125,121.796560,28.938840,29.490395,28.125658,0.765919,0.733267,0.667208,...,-0.056916,32.996635,0.000273,1802.50200,-0.048038,32.818672,0.000274,1776.0543,-0.036352,32.477330
1,1,115.114370,114.13390,114.780940,40.002388,39.992800,39.085606,-0.128434,-0.205653,-0.297164,...,0.153613,40.516262,0.000223,2723.43630,0.142375,40.734493,0.000221,2751.6210,0.134044,40.949207
2,2,159.694690,159.56078,159.059370,22.396538,22.786140,21.196556,-0.900852,-0.889049,-0.819917,...,0.099676,23.358757,0.000451,923.12820,0.093207,23.493671,0.000449,926.9788,0.090818,23.602468
3,3,128.605000,129.45172,129.037960,36.430650,31.820166,27.875772,0.270808,0.176806,-0.032982,...,-0.024913,37.640762,0.000242,2201.84800,-0.053031,38.163292,0.000244,2248.1099,-0.075183,38.606953
4,4,131.279070,129.53406,127.395935,47.384743,43.812016,40.883484,0.392003,0.247938,0.176773,...,0.014999,49.398335,0.000210,3901.51370,0.000607,49.812344,0.000213,3976.8184,-0.016899,50.414196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,295,128.657800,133.75015,138.841570,16.417543,16.632872,17.001358,0.286247,0.351475,0.320209,...,0.090834,17.566576,0.000488,509.19208,0.068692,17.779747,0.000487,518.0503,0.052453,17.955776
296,296,121.682190,119.31219,116.371560,30.490591,31.102995,31.828580,-0.214544,-0.268230,-0.343551,...,0.188520,31.013780,0.000250,1560.58750,0.187295,31.061867,0.000248,1561.0020,0.187751,31.211184
297,297,119.152970,120.71562,122.111404,29.647953,26.525736,24.341430,0.307116,0.363180,0.327180,...,-0.104344,32.654220,0.000266,1626.17850,-0.115476,32.735760,0.000267,1641.1764,-0.123704,32.750202
298,298,156.023740,156.10437,152.670780,34.913746,30.280325,26.674183,-0.584971,-0.641547,-0.807623,...,-0.103597,37.791540,0.000259,2143.84990,-0.124734,38.292564,0.000267,2189.4956,-0.147755,38.728090
299,299,122.114685,121.23281,121.003590,29.946177,28.144718,27.131632,0.384587,0.431959,0.423652,...,-0.058454,33.125140,0.000263,1705.24320,-0.057036,32.878006,0.000266,1705.3346,-0.055076,32.711906

In [20]:
X.drop(['Unnamed: 0'], axis=1, inplace=True)

In [21]:
X

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F25,F26,F27,F28,F29,F30,F31,F32,F33,F34
0,127.285160,128.014220,129.049220,23.132183,22.989187,23.550589,-0.300963,-0.312428,-0.305175,-0.663248,...,0.198341,22.986380,0.000363,881.44050,0.171260,23.502848,0.000357,907.04840,0.146760,23.971640
1,123.675316,124.864530,125.766250,17.833525,18.399496,18.087454,0.246668,0.214148,0.209875,1.059606,...,-0.001439,20.156706,0.000452,680.20935,-0.028413,20.362183,0.000453,695.33453,-0.047140,20.576350
2,132.912500,133.320470,132.442660,25.895767,25.280909,23.832703,0.305303,0.368690,0.455977,-0.317954,...,-0.052314,29.969877,0.000290,1368.54590,-0.069415,30.148418,0.000292,1390.66440,-0.084887,30.371254
3,110.283905,113.433280,116.918750,30.094240,27.083897,24.573830,0.492504,-0.017867,-0.921990,0.409154,...,0.009663,26.342894,0.000498,1508.64470,-0.003699,26.670254,0.000491,1527.80180,-0.017576,27.039417
4,91.065940,106.395000,118.473750,20.735636,20.307592,19.412655,1.985061,1.934323,1.916436,6.443342,...,0.032211,19.772793,0.000550,807.46770,0.019337,19.910126,0.000544,829.33936,-0.000955,20.209100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,116.856560,114.497345,111.954840,41.003567,38.772100,36.618973,0.569956,0.620960,0.647937,-0.385474,...,0.210192,37.396090,0.000225,2455.31570,0.198277,37.753640,0.000230,2491.52880,0.187167,37.971317
696,159.455780,151.456250,143.326870,43.487637,42.923706,38.616272,-0.854458,-0.841975,-0.881015,0.053559,...,0.015246,47.091972,0.000224,3693.84030,-0.006851,47.803320,0.000226,3756.04050,-0.026491,48.188270
697,134.612980,132.746570,128.173900,45.607872,43.689130,41.025510,-0.326999,-0.330075,-0.334550,-0.691699,...,0.115463,46.382470,0.000202,3476.26540,0.099332,46.946045,0.000199,3514.17240,0.088212,47.377182
698,125.118126,124.585000,124.452190,32.311893,29.621923,26.401573,0.339743,0.328440,0.272559,-0.502151,...,0.155644,30.449928,0.000263,1492.23390,0.164374,30.227848,0.000263,1495.68580,0.162392,30.338568
699,111.085310,111.054220,111.086716,44.621025,43.527970,41.746906,0.445195,0.357870,0.237632,-0.428429,...,0.289028,39.423650,0.000226,2743.13750,0.280644,39.682438,0.000228,2779.69210,0.271496,40.099503

In [22]:
Y.drop(['Unnamed: 0'], axis=1, inplace=True)

In [23]:
Y

       0
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
..   ...
695  1.0
696  1.0
697  1.0
698  1.0
699  1.0

[700 rows x 1 columns]

In [24]:
Z.drop(['Unnamed: 0'], axis=1, inplace=True)

In [25]:
Z

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F25,F26,F27,F28,F29,F30,F31,F32,F33,F34
0,122.072815,121.53125,121.796560,28.938840,29.490395,28.125658,0.765919,0.733267,0.667208,0.466528,...,-0.056916,32.996635,0.000273,1802.50200,-0.048038,32.818672,0.000274,1776.0543,-0.036352,32.477330
1,115.114370,114.13390,114.780940,40.002388,39.992800,39.085606,-0.128434,-0.205653,-0.297164,-0.067868,...,0.153613,40.516262,0.000223,2723.43630,0.142375,40.734493,0.000221,2751.6210,0.134044,40.949207
2,159.694690,159.56078,159.059370,22.396538,22.786140,21.196556,-0.900852,-0.889049,-0.819917,-0.284183,...,0.099676,23.358757,0.000451,923.12820,0.093207,23.493671,0.000449,926.9788,0.090818,23.602468
3,128.605000,129.45172,129.037960,36.430650,31.820166,27.875772,0.270808,0.176806,-0.032982,-0.920561,...,-0.024913,37.640762,0.000242,2201.84800,-0.053031,38.163292,0.000244,2248.1099,-0.075183,38.606953
4,131.279070,129.53406,127.395935,47.384743,43.812016,40.883484,0.392003,0.247938,0.176773,-0.538484,...,0.014999,49.398335,0.000210,3901.51370,0.000607,49.812344,0.000213,3976.8184,-0.016899,50.414196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,128.657800,133.75015,138.841570,16.417543,16.632872,17.001358,0.286247,0.351475,0.320209,0.423895,...,0.090834,17.566576,0.000488,509.19208,0.068692,17.779747,0.000487,518.0503,0.052453,17.955776
296,121.682190,119.31219,116.371560,30.490591,31.102995,31.828580,-0.214544,-0.268230,-0.343551,-0.185487,...,0.188520,31.013780,0.000250,1560.58750,0.187295,31.061867,0.000248,1561.0020,0.187751,31.211184
297,119.152970,120.71562,122.111404,29.647953,26.525736,24.341430,0.307116,0.363180,0.327180,-0.536232,...,-0.104344,32.654220,0.000266,1626.17850,-0.115476,32.735760,0.000267,1641.1764,-0.123704,32.750202
298,156.023740,156.10437,152.670780,34.913746,30.280325,26.674183,-0.584971,-0.641547,-0.807623,-0.141712,...,-0.103597,37.791540,0.000259,2143.84990,-0.124734,38.292564,0.000267,2189.4956,-0.147755,38.728090
299,122.114685,121.23281,121.003590,29.946177,28.144718,27.131632,0.384587,0.431959,0.423652,-0.064413,...,-0.058454,33.125140,0.000263,1705.24320,-0.057036,32.878006,0.000266,1705.3346,-0.055076,32.711906

In [26]:
shape_X = X.shape
shape_Y = Y.shape
shape_Z = Z.shape
m = (X.size)/shape_X[0]  # training set size
### END CODE HERE ###

print ('The shape of X is: ' + str(shape_X))
print ('The shape of Y is: ' + str(shape_Y))
print ('The shape of Z is: ' + str(shape_Z))
print ('We have m = %d training examples' % (m))

The shape of X is: (700, 34)
The shape of Y is: (700, 1)
The shape of Z is: (300, 34)
We have m = 34 training examples

In [150]:
clas = MLPClassifier(solver='adam', alpha=0.0004, hidden_layer_sizes=(50, 30, 10, 5), random_state=0)
clas.fit(X, Y['0'].tolist())

MLPClassifier(alpha=0.0004, hidden_layer_sizes=(50, 30, 10, 5), random_state=0)

In [151]:
clas.predict_proba(Z[:])

array([[6.72442645e-01, 3.27557355e-01],
       [3.57445762e-01, 6.42554238e-01],
       [4.26280447e-01, 5.73719553e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [8.22853312e-01, 1.77146688e-01],
       [9.71639114e-01, 2.83608861e-02],
       [3.57445762e-01, 6.42554238e-01],
       [9.99537900e-01, 4.62100188e-04],
       [6.45531685e-01, 3.54468315e-01],
       [7.57375429e-01, 2.42624571e-01],
       [3.57445762e-01, 6.42554238e-01],
       [8.80772784e-01, 1.19227216e-01],
       [3.57445762e-01, 6.42554238e-01],
       [6.44036867e-01, 3.55963133e-01],
       [9.99939509e-01, 6.04914448e-05],
       [7.99879584e-01, 2.00120416e-01],
       [6.75408980e-01, 3.24591020e-01],
       [7.05063868e-01, 2.94936132e-01],
       [9.95278896e-01, 4.72110388e-03],
       [6.29364429e-01, 3.70635571e-01],
       [3.57445762e-01, 6.42554238e-01],
       [5.49441835e-01, 4.50558165e-01],
       [3.57445762e-01, 6.42554238e-01],
       [7.57486334e-01, 2.42513666e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.23470528e-01, 7.65294719e-02],
       [5.94792631e-01, 4.05207369e-01],
       [9.99710507e-01, 2.89493081e-04],
       [9.99758069e-01, 2.41931227e-04],
       [8.56576184e-01, 1.43423816e-01],
       [8.75928825e-01, 1.24071175e-01],
       [9.08558778e-01, 9.14412218e-02],
       [3.57445762e-01, 6.42554238e-01],
       [8.23590186e-01, 1.76409814e-01],
       [4.37727880e-01, 5.62272120e-01],
       [8.52053269e-01, 1.47946731e-01],
       [9.99023697e-01, 9.76303181e-04],
       [3.57445762e-01, 6.42554238e-01],
       [5.06591751e-01, 4.93408249e-01],
       [3.98031703e-01, 6.01968297e-01],
       [8.36304947e-01, 1.63695053e-01],
       [9.59838748e-01, 4.01612520e-02],
       [3.72581963e-01, 6.27418037e-01],
       [7.95307908e-01, 2.04692092e-01],
       [3.57445762e-01, 6.42554238e-01],
       [8.29937588e-01, 1.70062412e-01],
       [4.46904869e-01, 5.53095131e-01],
       [5.12771786e-01, 4.87228214e-01],
       [9.38717591e-01, 6.12824094e-02],
       [8.52540729e-01, 1.47459271e-01],
       [9.07768084e-01, 9.22319163e-02],
       [4.57674536e-01, 5.42325464e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.22191907e-01, 7.78080929e-02],
       [5.14611775e-01, 4.85388225e-01],
       [3.57445762e-01, 6.42554238e-01],
       [7.93695873e-01, 2.06304127e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.99991255e-01, 8.74515194e-06],
       [4.60412775e-01, 5.39587225e-01],
       [7.04138873e-01, 2.95861127e-01],
       [7.09573507e-01, 2.90426493e-01],
       [3.84303997e-01, 6.15696003e-01],
       [6.08946596e-01, 3.91053404e-01],
       [3.57445762e-01, 6.42554238e-01],
       [6.08860129e-01, 3.91139871e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.99926200e-01, 7.37999267e-05],
       [8.28287659e-01, 1.71712341e-01],
       [9.11537415e-01, 8.84625854e-02],
       [8.49363936e-01, 1.50636064e-01],
       [4.39073496e-01, 5.60926504e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.59664940e-01, 4.03350597e-02],
       [9.28526805e-01, 7.14731952e-02],
       [3.57445762e-01, 6.42554238e-01],
       [9.96324313e-01, 3.67568683e-03],
       [7.86547307e-01, 2.13452693e-01],
       [6.95901762e-01, 3.04098238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [7.22512847e-01, 2.77487153e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.43951130e-01, 5.60488700e-02],
       [5.15907971e-01, 4.84092029e-01],
       [9.99998389e-01, 1.61147730e-06],
       [9.46879215e-01, 5.31207851e-02],
       [8.56541809e-01, 1.43458191e-01],
       [6.48953044e-01, 3.51046956e-01],
       [5.08059467e-01, 4.91940533e-01],
       [9.97515328e-01, 2.48467204e-03],
       [3.57445762e-01, 6.42554238e-01],
       [4.67512080e-01, 5.32487920e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [5.39456369e-01, 4.60543631e-01],
       [3.57445762e-01, 6.42554238e-01],
       [5.08520902e-01, 4.91479098e-01],
       [8.94241913e-01, 1.05758087e-01],
       [8.68455232e-01, 1.31544768e-01],
       [3.57445762e-01, 6.42554238e-01],
       [1.00000000e+00, 1.37601296e-15],
       [9.01062737e-01, 9.89372633e-02],
       [5.07935124e-01, 4.92064876e-01],
       [4.58212198e-01, 5.41787802e-01],
       [8.59382231e-01, 1.40617769e-01],
       [3.57445762e-01, 6.42554238e-01],
       [5.17595665e-01, 4.82404335e-01],
       [8.67274180e-01, 1.32725820e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.99998134e-01, 1.86638131e-06],
       [4.84443540e-01, 5.15556460e-01],
       [3.57445762e-01, 6.42554238e-01],
       [7.71497994e-01, 2.28502006e-01],
       [9.98729541e-01, 1.27045931e-03],
       [9.69334895e-01, 3.06651046e-02],
       [9.47425819e-01, 5.25741814e-02],
       [3.57445762e-01, 6.42554238e-01],
       [5.59065503e-01, 4.40934497e-01],
       [3.57445762e-01, 6.42554238e-01],
       [6.40049807e-01, 3.59950193e-01],
       [9.84768587e-01, 1.52314131e-02],
       [3.77813197e-01, 6.22186803e-01],
       [8.09811135e-01, 1.90188865e-01],
       [9.04139763e-01, 9.58602374e-02],
       [8.86881000e-01, 1.13119000e-01],
       [9.70293940e-01, 2.97060599e-02],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.73380198e-01, 2.66198023e-02],
       [9.36703689e-01, 6.32963113e-02],
       [1.00000000e+00, 1.21023978e-14],
       [9.71626705e-01, 2.83732951e-02],
       [9.99999699e-01, 3.00938774e-07],
       [8.63785762e-01, 1.36214238e-01],
       [9.72214315e-01, 2.77856853e-02],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [8.53382703e-01, 1.46617297e-01],
       [8.64820672e-01, 1.35179328e-01],
       [9.89196523e-01, 1.08034766e-02],
       [9.14833955e-01, 8.51660449e-02],
       [3.57445762e-01, 6.42554238e-01],
       [9.10187699e-01, 8.98123010e-02],
       [9.06183100e-01, 9.38169002e-02],
       [8.30380717e-01, 1.69619283e-01],
       [8.12591381e-01, 1.87408619e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.92844179e-01, 7.15582135e-03],
       [3.57445762e-01, 6.42554238e-01],
       [8.37381524e-01, 1.62618476e-01],
       [9.88090461e-01, 1.19095388e-02],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [1.00000000e+00, 8.32352010e-19],
       [5.66242823e-01, 4.33757177e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.27586012e-01, 7.24139878e-02],
       [6.09029708e-01, 3.90970292e-01],
       [7.69733277e-01, 2.30266723e-01],
       [9.49715806e-01, 5.02841937e-02],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [4.25926861e-01, 5.74073139e-01],
       [9.86764087e-01, 1.32359131e-02],
       [9.74410534e-01, 2.55894657e-02],
       [3.57445762e-01, 6.42554238e-01],
       [8.36839375e-01, 1.63160625e-01],
       [5.06057335e-01, 4.93942665e-01],
       [9.86726391e-01, 1.32736085e-02],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [6.49149204e-01, 3.50850796e-01],
       [3.69578459e-01, 6.30421541e-01],
       [9.57812826e-01, 4.21871744e-02],
       [3.74967915e-01, 6.25032085e-01],
       [9.29623735e-01, 7.03762653e-02],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.53089142e-01, 4.69108580e-02],
       [8.62330502e-01, 1.37669498e-01],
       [9.30362280e-01, 6.96377199e-02],
       [3.61067815e-01, 6.38932185e-01],
       [7.63294333e-01, 2.36705667e-01],
       [4.78652371e-01, 5.21347629e-01],
       [7.11250695e-01, 2.88749305e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [8.31569003e-01, 1.68430997e-01],
       [9.99998858e-01, 1.14247009e-06],
       [9.98267186e-01, 1.73281431e-03],
       [7.70813666e-01, 2.29186334e-01],
       [7.43984278e-01, 2.56015722e-01],
       [6.31748701e-01, 3.68251299e-01],
       [7.03751418e-01, 2.96248582e-01],
       [8.75580480e-01, 1.24419520e-01],
       [9.72541029e-01, 2.74589708e-02],
       [7.55717863e-01, 2.44282137e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.87530722e-01, 1.24692780e-02],
       [9.99996958e-01, 3.04199293e-06],
       [9.87459269e-01, 1.25407314e-02],
       [3.57445762e-01, 6.42554238e-01],
       [9.39812323e-01, 6.01876765e-02],
       [7.57609499e-01, 2.42390501e-01],
       [9.74166060e-01, 2.58339405e-02],
       [3.57445762e-01, 6.42554238e-01],
       [5.89001368e-01, 4.10998632e-01],
       [5.87399658e-01, 4.12600342e-01],
       [3.57445762e-01, 6.42554238e-01],
       [6.12545072e-01, 3.87454928e-01],
       [4.94936955e-01, 5.05063045e-01],
       [3.60694688e-01, 6.39305312e-01],
       [6.52622914e-01, 3.47377086e-01],
       [7.25854235e-01, 2.74145765e-01],
       [8.78150562e-01, 1.21849438e-01],
       [6.35636351e-01, 3.64363649e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [8.89476013e-01, 1.10523987e-01],
       [3.57445762e-01, 6.42554238e-01],
       [6.97961209e-01, 3.02038791e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [8.89102182e-01, 1.10897818e-01],
       [9.08871821e-01, 9.11281787e-02],
       [9.99994526e-01, 5.47441170e-06],
       [3.57445762e-01, 6.42554238e-01],
       [4.76647462e-01, 5.23352538e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.74840541e-01, 6.25159459e-01],
       [8.30876177e-01, 1.69123823e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.99386733e-01, 6.13267282e-04],
       [9.99889033e-01, 1.10966513e-04],
       [9.99754206e-01, 2.45793649e-04],
       [3.57445762e-01, 6.42554238e-01],
       [3.59177338e-01, 6.40822662e-01],
       [5.98074602e-01, 4.01925398e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.88036292e-01, 1.19637082e-02],
       [9.99998588e-01, 1.41202851e-06],
       [7.16282077e-01, 2.83717923e-01],
       [9.99742287e-01, 2.57712689e-04],
       [8.61752239e-01, 1.38247761e-01],
       [3.57445762e-01, 6.42554238e-01],
       [8.17568179e-01, 1.82431821e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [8.57129975e-01, 1.42870025e-01],
       [6.29933570e-01, 3.70066430e-01],
       [8.48739720e-01, 1.51260280e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.19308949e-01, 8.06910512e-02],
       [9.95910639e-01, 4.08936096e-03],
       [6.02848471e-01, 3.97151529e-01],
       [7.42910566e-01, 2.57089434e-01],
       [8.27595238e-01, 1.72404762e-01],
       [8.84650280e-01, 1.15349720e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.93882423e-01, 6.11757743e-03],
       [4.85364667e-01, 5.14635333e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.92332550e-01, 7.66744987e-03],
       [3.57445762e-01, 6.42554238e-01],
       [9.57394567e-01, 4.26054332e-02],
       [8.64834519e-01, 1.35165481e-01],
       [1.00000000e+00, 9.83951021e-14],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [9.95268124e-01, 4.73187565e-03],
       [8.91396586e-01, 1.08603414e-01],
       [5.27007855e-01, 4.72992145e-01],
       [9.72765627e-01, 2.72343726e-02],
       [9.28688768e-01, 7.13112316e-02],
       [8.08202317e-01, 1.91797683e-01],
       [3.57445762e-01, 6.42554238e-01],
       [8.22598006e-01, 1.77401994e-01],
       [8.35024703e-01, 1.64975297e-01],
       [7.10667691e-01, 2.89332309e-01],
       [7.50598131e-01, 2.49401869e-01],
       [4.04159879e-01, 5.95840121e-01],
       [9.89239354e-01, 1.07606461e-02],
       [4.24102662e-01, 5.75897338e-01],
       [8.19747680e-01, 1.80252320e-01],
       [6.36612556e-01, 3.63387444e-01],
       [3.57445762e-01, 6.42554238e-01],
       [3.57445762e-01, 6.42554238e-01],
       [4.71529736e-01, 5.28470264e-01]])

In [152]:
pred=clas.predict(Z)
df_pred=pd.DataFrame(data=pred)

In [153]:
df_pred

       0
0    0.0
1    1.0
2    1.0
3    1.0
4    1.0
..   ...
295  0.0
296  0.0
297  1.0
298  1.0
299  1.0

[300 rows x 1 columns]

In [154]:
df_pred.loc[df_pred[0]==0.0, "class"] = "Non_raveling"
df_pred.loc[df_pred[0]==1.0, "class"] = "Raveling"

In [155]:
df_pred

       0         class
0    0.0  Non_raveling
1    1.0      Raveling
2    1.0      Raveling
3    1.0      Raveling
4    1.0      Raveling
..   ...           ...
295  0.0  Non_raveling
296  0.0  Non_raveling
297  1.0      Raveling
298  1.0      Raveling
299  1.0      Raveling

[300 rows x 2 columns]

In [156]:
df_pred.drop([0], axis=1, inplace=True)

In [157]:
df_pred

            class
0    Non_raveling
1        Raveling
2        Raveling
3        Raveling
4        Raveling
..            ...
295  Non_raveling
296  Non_raveling
297      Raveling
298      Raveling
299      Raveling

[300 rows x 1 columns]

In [158]:
df_pred.to_csv("New_pred13.csv")

In [159]:
os.getcwd()

'C:\\Users\\DELL\\Downloads'

In [160]:
data=pd.DataFrame(df_pred)

In [88]:
data

        class
0    Raveling
1    Raveling
2    Raveling
3    Raveling
4    Raveling
..        ...
295  Raveling
296  Raveling
297  Raveling
298  Raveling
299  Raveling

[300 rows x 1 columns]